### ISSUE TITLE
GitHub Guidelines *READ THIS FIRST*

### ISSUE THREAD

**Issue by DocFox55** [felicityfields/server#7]
When posting or adding Issues and other content, use the following format:

Title - Should be accurate, brief, and clear

Use bullet points for each idea or thought. 

Example:

- **Collaboration is Key**: (Provide description here)

**Comment by callmemantas** [comment]
I can set up proper contributing guidelines. It doesn’t really make sense to have an issue for an informational post because you can’t “sticky” an issue. If I’d have more access to the repository, I could make this place [much easier to traverse](https://github.com/callmemantas/goggles).

**Comment by callmemantas** [comment]
I have added the contributing guidelines to the repository files, check `CONTRIBUTING.md`.
